
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/ToastProvider";
// import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
// const pathname = usePathname();
// const isCheckout = pathname.startsWith("/checkout");

export const metadata = {
  title: "Dr. Vandy's",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main
          className="page-wrapper"
          // styles={{ backgroundColor: isCheckout ? "#fcfdf8" : "#fcfdf8" }}
        >
          <ToastProvider>
            {children} {/* All pages/components go here */}
          </ToastProvider>
        </main>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: "Dr. Vandy's",
              url: "https://drvandys.com",
            }),
          }}
        />
      </body>
    </html>
  );
}
